### ISSUE TITLE
Norm gradient

### ISSUE THREAD

**Issue by lorenzosteccanella** [cvxgrp/dccp#75]
Hi all,

I'm new to optimization and DCCP.

I have the following minimum example of my problem:

```
X = cvx.Variable((2, 1), name="X")
Y = cvx.Variable((2, 1), name="Y")
C = cvx.Parameter((2), name="C")

X.value = np.array([[10], [20]])
Y.value = np.array([[10], [10]])
C.value = np.array([1, 1])
obj = cvx.Maximize(cvx.sum(cvx.norm(X - Y, 2, axis=1), axis=0))
constr = [cvx.norm(X - Y, 2, axis=1) <= C]
myprob = cvx.Problem(obj, constr)

grad_map = obj.expr.grad()
```

so from my problem the only concave part that need to be linearized is the objective but I get the following error:
`    D = D + sp.csc_matrix((np.array(d)[0], (row, col)),
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed`

Due by the fact that we have (10-10), I know I can directly manage it by removing it, but I have some reason for not solving it in this way.

Moreover I get the same error even with correct values of X and Y when I use l1 norm instead of l2.

What am I doing wrong?

ps: I'm trying to takkle this problem with the Concave Convex procedure but if you do have some better idea on how to solve it please let me know.

Thanks!

**Comment by xinyueshen** [comment]
Hi @lorenzosteccanella thank you for reporting the error. There was a bug in gradient computation in CVXPY, and the bug is now fixed, so it should be able to work for your example. We'll merge the updated code into the master branch of CVXPY, but if you want to try it now, please reinstall CVXPY from source in this forked repo https://github.com/xinyueshen/cvxpy.

**Comment by xinyueshen** [comment]
By the way, for the specific example that you posted, due to monotonicity the problem is equivalent to `cvx.Maximize(cvx.sum(C))`, so the optimal value is just `C[0] + C[1]`, and no solver is needed. (Ignore this if it is just your test example.)

**Comment by lorenzosteccanella** [comment]
Hi @xinyueshen,

thanks a lot for your help, I guess you solved the main issue but I still get an error if I increase the dimensions, for both l1 and l2:

```
X = cvx.Variable((2, 2), name="X")
Y = cvx.Variable((2, 2), name="Y")
C = cvx.Parameter((2), name="C")

X.value = np.array([[10, 10], [20, 10]])
Y.value = np.array([[10, 10], [10, 10]])
C.value = np.array([1, 1])
obj = cvx.Maximize(cvx.sum(cvx.norm(X - Y, 1, axis=1), axis=0))
constr = [cvx.norm(X - Y, 1, axis=1) <= C]
myprob = cvx.Problem(obj, constr)

grad_map = obj.expr.grad()
```

error:

`ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,) and requested shape (1,1)`

am I doing something wrong?

Thanks a lot!

**Comment by xinyueshen** [comment]
Hi @lorenzosteccanella the bug is fixed, and to try the updated code please reinstall CVXPY again from source in this forked repo https://github.com/xinyueshen/cvxpy.
